name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Version and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'pnpm'

      - run: pnpm install

      - name: Create GitHub Release
        uses: changesets/action@v1
        with:
          version: npx changeset version
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"
