name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Version and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.6

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - name: Version packages
        run: pnpm changeset version

      - name: Create GitHub Release
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: echo "no publish step, only release created"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
